//GET https://firebasestorage.googleapis.com/v0/b/techblog-e0db2.appspot.com/o/pexels-googledeepmind-17485609.jpg?alt=media&token=872eb76b-0ad4-402c-a801-acff7ad17452

GET https://tailwind-blog-peach.vercel.app/blog/image-recognition